Add some infos when an exception occurs in resize_image
The error i often get is inside /site-packages/PIL/Image.py, line 1943:
TypeError: an integer is required (got type NoneType)